
define([
    'jquery',
], function(jQuery) {

    return [
        ["'Tippecanoe and Tyler Too'", "William Henry Harrison, 1840", "WilliamHenryHarrison.jpg", "center", "Harrison was the first person to actively campaign for office — and why not intimidate the competition with a sick rhyme game? To explain: Harrison was considered the 'hero of Tippecanoe,' a 1811 battle he led against warrior Tecumseh. The Whig did win the election — but died a month after taking office, with running-mate John Tyler succeeding him. Tippecanoe and Tyler Too, indeed."],
        ["'Who is James K. Polk?'", "Henry Clay, 1844", "henryclay.jpg", "center", "Slow-clap to Henry Clay, master of the freeze-out before it was cool. The least we can do is honor his brazenness: He ended up losing to James K. Polk in a super-tight, bitter election mired in politics over slavery."],
        ["'We Polked You in '44, We Shall Pierce You in '52'", "Franklin Pierce, 1852", "franklinpierce_final.jpg", "center", "Like a dagger to the heart, these political puns. Little-known Democrat Pierce made the most of his last name, following up his party’s win with James K. Polk in 1844 with a surprise victory in ’52. Note to 2016 candidates: slightly menacing slogans with dirty undertones rock the vote."],
        ["'Don't change horses in midstream'", "Abraham Lincoln, 1864", "abelincoln_final.jpg", "center", "Abolishing slavery! Cobbling together a war-torn nation! Using topical, and exceedingly literal campaign slogans! Next time your gaze upon a copper-coated Abraham Lincoln, ponder these accomplishments. Because we all know that changing horses midstream is probably a poor decision, and so did the American people who kept him in office."],
        ["'Blaine, Blaine, James G. Blaine, the Continental Liar from the State of Maine'", "Grover Cleveland, 1884", "grovercleveland_final.jpg", "center", "If in doubt, call your opponent a liar from the Great North. In his 1884 campaign, Cleveland attacked opponent Blaine’s dodgy railroad industry involvement. Spoiler alert: Cleveland (narrowly) won."],
        ["'Ma, Ma, Where’s my Pa, Gone to the White House, Ha, Ha, Ha'", "James Blaine, 1884", "jamesgblaine_final.jpg", "center", "If your opponent calls you a liar from the Great North, accuse them of having an illegitimate child and start a chant about it. And so, Blaine’s Cleveland-targeted ads were created, and the political smear campaign game was forever upped."],
        ["'Keep Cool and Keep Coolidge'", "Calvin Coolidge, 1924", "coolidge_final.jpg", "center", "This is, bar none, *the* coolest campaign slogan in the U.S.’ storied political history. Fun fact: the slogan was turned into a popular song written by Ida Cheever Goodwin with music by Bruce Harper. Time to change the 'Silent Cal' nickname to 'LL-Coolidge-J'? We think yes."],
        ["'A chicken in every pot and a car in every garage'", "Herbert Hoover, 1928", "HerbertHoover.jpg", "center", "Hoover, how about a promise you could keep? During his presidential run during the Great Depression, the Republican promised the American dream to struggling citizens. He was a winner, winner over Alfred Smith — but whatever happened to the chicken dinner? Hoover was not re-elected for a second term."],
        ["'Roosevelt for Ex-President'", "Wendell Willkie, 1940", "Willkie.jpg", "center", "When you’re out of your league, go for what people know — hating the status quo. Republican Willkie went out punching against president Franklin D. Roosevelt in this simple and direct campaign ad. He ended up losing, but FDR appointed him an informal ambassador-at-large. Win-win, W.W."],
        ["'I like Ike'", "Dwight D. Eisenhower, 1952", "ike1_final.jpg", "center", "Ike = innovation! The 'I like Ike' moniker came from market research that showed how much people trusted Ike (aka Eisenhower). The campaign slogan became omnipresent before the 1952 election against Adlai Stevenson. Along with a song by Irving Berlin (considered one of America’s great musicians), Walt Disney Studios made a TV spot for the campaign featuring an adorable elephant, the first political ads to air on TV. "],
        ["'I still like Ike'", "Dwight D. Eisenhower, 1952", "Ike2_final.jpg", "center", "Hey, if it ain’t broke, don’t fix it! Ike was elected the maximum of two times, succeeded by John F. Kennedy."],
        ["'In Your Guts, You Know He's Nuts'", "Lyndon B. Johnson, 1964", "LBJ.jpg", "center", "The Democrats came out swinging with this attack slogan against opponent Barry Goldwater’s catch-phrase, 'In your heart you know he’s right.' Other alternate retorts: 'In your heart you know he’s right, yes, extreme right' and 'In your heart you know he might.' Shocker — LBJ won by a landslide, capturing 44 states and D.C."],
        ["'Not Just Peanuts'", "Jimmy Carter, 1976", "JimmyCarter.jpg", "center", "Oh, Jimmy Carter, that Georgia peanut farmer-turned politician with a heart of gold. The democrat’s campaign slogan alluded to his broad experience while reminding voters of his humble beginnings. Plus, it makes us giggle."],
        ["'Ross for Boss'", "Ross Perot, 1992", "ROSSPEROT.jpg", "center", "He was the boss, literally — but he was never president. Perot, who ran as an independent in 1992 and as part of the Reform Party in 1996 (and lost both times, of course), has a net worth of $5.6 billion. Take that, Donald Trump."],
        ["'Defeat the Washington machine. Unleash the American dream'", "Rand Paul, 2016", "RandPaul.jpg", "center", "For those looking to rage against the machine, Paul’s slogan may gain some traction in the upcoming presidential election. But for everyday voters, his anti-establishment campaign is a bit of a head-scratcher (or hair-tousler?) — especially because as a senator in Washington, he’s, well, part of the machine.​"],
        ];

});

